name: Validate JSON Schema

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jsonschema
    
    - name: Validate schema files
      run: |
        python -c "
import json
import jsonschema
from jsonschema import validate
from jsonschema.validators import Draft7Validator

# Load the schema
with open('schema/business_loan_schema.v0.1.2.json', 'r') as f:
    schema = json.load(f)

# Validate the schema itself
Draft7Validator.check_schema(schema)
print('Schema is valid!')
" 