name: Validate JSON Schema

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install check-jsonschema
      run: |
        python -m pip install --upgrade pip
        pip install check-jsonschema
    
    - name: Validate schema files
      run: |
        check-jsonschema --builtin-schema draft-07 schema/*.json 